apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blogflow.fullname" . }}
  labels:
    {{- include "blogflow.labels" . | nindent 4 }}
data:
  site.yaml: |
    {{- $config := deepCopy .Values.siteConfig -}}
    {{- if and .Values.service.metricsPort (gt (int .Values.service.metricsPort) 0) -}}
      {{- $_ := set $config.server "metrics_port" (int .Values.service.metricsPort) -}}
    {{- end }}
    {{- $config | toYaml | nindent 4 }}
