{{- if and (eq .Values.sync.strategy "webhook") (not .Values.sync.webhook.existingSecret) .Values.sync.webhook.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blogflow.fullname" . }}-webhook
  labels:
    {{- include "blogflow.labels" . | nindent 4 }}
type: Opaque
stringData:
  webhook-secret: {{ .Values.sync.webhook.secret | quote }}
{{- end }}
